"""Add association proxies for relationship between devs and companies

Revision ID: 10fff4f0e27e
Revises: 3a67d405ec9a
Create Date: 2025-05-25 05:49:59.602350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10fff4f0e27e'
down_revision = '3a67d405ec9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
