"""Add cascade for deletion in dev_event and company_event tables

Revision ID: 2e800edabde8
Revises: 9873510dabb6
Create Date: 2025-05-25 07:50:28.401546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e800edabde8'
down_revision = '9873510dabb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_event', schema=None) as batch_op:
        batch_op.drop_constraint('fk_company_event_event_id_events', type_='foreignkey')
        batch_op.drop_constraint('fk_company_event_company_id_companies', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_company_event_company_id_companies'), 'companies', ['company_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_company_event_event_id_events'), 'events', ['event_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('dev_event', schema=None) as batch_op:
        batch_op.drop_constraint('fk_dev_event_dev_id_devs', type_='foreignkey')
        batch_op.drop_constraint('fk_dev_event_event_id_events', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_dev_event_event_id_events'), 'events', ['event_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_dev_event_dev_id_devs'), 'devs', ['dev_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dev_event', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_dev_event_dev_id_devs'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_dev_event_event_id_events'), type_='foreignkey')
        batch_op.create_foreign_key('fk_dev_event_event_id_events', 'events', ['event_id'], ['id'])
        batch_op.create_foreign_key('fk_dev_event_dev_id_devs', 'devs', ['dev_id'], ['id'])

    with op.batch_alter_table('company_event', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_company_event_event_id_events'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_company_event_company_id_companies'), type_='foreignkey')
        batch_op.create_foreign_key('fk_company_event_company_id_companies', 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key('fk_company_event_event_id_events', 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###
