"""Remove direct relationship between Freebie and Event

Revision ID: 3a67d405ec9a
Revises: 9e0cc5b5f37c
Create Date: 2025-05-24 18:46:51.038116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a67d405ec9a'
down_revision = '9e0cc5b5f37c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freebies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_freebies_event_id_events', type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freebies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_freebies_event_id_events', 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###
