"""Change relationships to cascade deletion

Revision ID: 3d8f617f2a8f
Revises: ca902ca16404
Create Date: 2025-05-26 11:09:13.991641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8f617f2a8f'
down_revision = 'ca902ca16404'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
