"""Add Models and form relationships

Revision ID: 7177805594a0
Revises: 5f72c58bf48c
Create Date: 2025-05-24 12:23:31.371118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7177805594a0'
down_revision = '5f72c58bf48c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('organiser', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('date_held', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_event',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_event_company_id_companies')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_company_event_event_id_events')),
    sa.PrimaryKeyConstraint('company_id', 'event_id')
    )
    op.create_table('dev_event',
    sa.Column('dev_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dev_id'], ['devs.id'], name=op.f('fk_dev_event_dev_id_devs')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_dev_event_event_id_events')),
    sa.PrimaryKeyConstraint('dev_id', 'event_id')
    )
    op.create_table('freebies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('dev_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_freebies_company_id_companies')),
    sa.ForeignKeyConstraint(['dev_id'], ['devs.id'], name=op.f('fk_freebies_dev_id_devs')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_freebies_event_id_events')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry', sa.String(), nullable=True))

    with op.batch_alter_table('devs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devs', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('email')
        batch_op.drop_column('age')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('industry')

    op.drop_table('freebies')
    op.drop_table('dev_event')
    op.drop_table('company_event')
    op.drop_table('events')
    # ### end Alembic commands ###
