"""Change default to server_default for time

Revision ID: 9e0cc5b5f37c
Revises: 7177805594a0
Create Date: 2025-05-24 16:25:31.678660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0cc5b5f37c'
down_revision = '7177805594a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
