"""Modify cascade deletion

Revision ID: ca902ca16404
Revises: 2e800edabde8
Create Date: 2025-05-25 11:53:08.735590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca902ca16404'
down_revision = '2e800edabde8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_event', schema=None) as batch_op:
        batch_op.drop_constraint('fk_company_event_event_id_events', type_='foreignkey')
        batch_op.drop_constraint('fk_company_event_company_id_companies', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_company_event_event_id_events'), 'events', ['event_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_company_event_company_id_companies'), 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('dev_event', schema=None) as batch_op:
        batch_op.drop_constraint('fk_dev_event_dev_id_devs', type_='foreignkey')
        batch_op.drop_constraint('fk_dev_event_event_id_events', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_dev_event_event_id_events'), 'events', ['event_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_dev_event_dev_id_devs'), 'devs', ['dev_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dev_event', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_dev_event_dev_id_devs'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_dev_event_event_id_events'), type_='foreignkey')
        batch_op.create_foreign_key('fk_dev_event_event_id_events', 'events', ['event_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_dev_event_dev_id_devs', 'devs', ['dev_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('company_event', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_company_event_company_id_companies'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_company_event_event_id_events'), type_='foreignkey')
        batch_op.create_foreign_key('fk_company_event_company_id_companies', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_company_event_event_id_events', 'events', ['event_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
